
services:
  web-notes:
    container_name: web-notes
    image: web-notes:latest
    build: .
    depends_on:
      - mongo-db
    environment:
      WEB_APP_NOTES_MONGODB_HOST: "mongo-db:27017"
      WEB_APP_NOTES_MONGODB_DATABASE: "web-notes"
    ports:
      - "4000:4000"
    networks:
      - notes-frontend
      - notes-backend

  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"
    networks:
      - notes-backend

  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    depends_on:
      - mongo-db
      - web-notes
      - mongo-express
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    networks:
      - notes-frontend

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    depends_on:
      - mongo-db
    environment:
      PORT: "8088"
      ME_CONFIG_MONGODB_URL: "mongodb://mongo-db:27017"
    ports:
      - "8088:8088"
    networks:
      - notes-frontend
      - notes-backend

volumes:
  database:

networks:
  notes-backend:
    internal: true
  notes-frontend:
