worker_processes auto;

events {
     worker_connections 1024;
}

http {

     ssl_certificate /etc/ssl/certs/localhost.crt;
     ssl_certificate_key /etc/ssl/private/localhost.key;

     server {
         listen 80;
         server_name web-notes-http;
         location / {
             return 301 https://$host$request_uri;
         }
     }

     server {
         listen 8081;
         server_name mongo-express-http;
         location / {
             return 301 https://$host:8081$request_uri;
          }
                    

     }

     server {
          listen 443 ssl;     
          server_name web-notes-https;
          location / {
               proxy_pass http://web-notes:4000/;
          }
     }
   
     server {
          listen 8081 ssl;
          server_name mongo-express-https;
          location / {
               proxy_pass http://mongo-express:8088/;
          }
     }
}
