server {
    listen 443;

    location / {
        proxy_pass http://web-notes-service:4000;
    }
}

server {
    listen 8081;

    location / {
        proxy_pass http://mongo-express-service:8088;
    }
}
