worker_processes auto;

events {
     worker_connections 1024;
}

http {

     server {
          listen 80;
          location / {
               return 301 https://$host$request_uri;
          }
     }

     server {
          ssl_certificate /etc/ssl/certs/localhost.crt;
          ssl_certificate_key /etc/ssl/private/localhost.key;
          listen 443 ssl;

          location / {
               proxy_pass http://web-notes:4000/;
          }
     }
   
     server {
          ssl_certificate /etc/ssl/certs/localhost.crt;
          ssl_certificate_key /etc/ssl/private/localhost.key;
          listen 8081 ssl;

          location / {
               proxy_pass http://mongo-express:8088/;
          }
     }
}
