worker_processes auto;

events {
     worker_connections 1024;
}

http {

     server {
         listen 80;
         location / {
             return 301 https://$host$request_uri;
         }

     }

     server {
          listen 443 ssl;

          ssl_certificate /etc/ssl/certs/localhost.crt;
          ssl_certificate_key /etc/ssl/private/localhost.key;

          location / {
               proxy_pass http://172.17.0.3:4000/;
          }
     }
   
     server {
          listen 8081 ssl;

          ssl_certificate /etc/ssl/certs/localhost.crt;
          ssl_certificate_key /etc/ssl/private/localhost.key;

          location / {
               proxy_pass http://172.17.0.4:8081/;
          }
     }
}
